apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: giropops-senhas
  namespace: argocd
spec:
  project: 'default'
  source:
    helm: {}
    repoURL: 'https://github.com/stenioignacio/descomplicando-gitops-no-kubernetes-com-argocd'
    targetRevision: feat/day2
    path: giropops-senhas/helm
  destination:
    namespace: giropops-senhas
    server: 'https://kubernetes.default.svc'
  syncPolicy:
    automated: {}
    syncOptions:
    - CreateNamespace=true
