apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: cluster-addons
  namespace: argocd
spec:
  goTemplate: true
  goTemplateOptions: [ "missingkey=error" ]
  generators:
  - matrix:
      generators:
      - git:
          repoURL: https://github.com/stenioignacio/descomplicando-gitops-no-kubernetes-com-argocd.git
          revision: feat/day3
          directories:
          - path: applicationset/apps/*/helm
          # Caso eu não queira usar um app especifico, eu passo o "exclude: true"
          # - path: applicationset/apps/random-logger/helm
          #   exclude: true
      - git:
          repoURL: https://github.com/stenioignacio/descomplicando-gitops-no-kubernetes-com-argocd.git
          revision: feat/day3
          pathParamPrefix: cfg
          files:
          - path: applicationset/configs/dev.json

  template:
    metadata:
      name: '{{index .path.segments 2}}-{{.cluster.name}}'
    spec:
      project: "default"
      source:
        repoURL: https://github.com/stenioignacio/descomplicando-gitops-no-kubernetes-com-argocd.git
        targetRevision: feat/day3
        path: '{{.path.path}}'
      destination:
        server: https://kubernetes.default.svc
        namespace: '{{index .path.segments 2}}'
      syncPolicy:
        automated: {}
        syncOptions:
        - CreateNamespace=true
